import React, { useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useResultContext } from '../context/ResultContextProvider';

export default function Home() {
  const { result, getLifeQuotes } = useResultContext();
  console.log(result);
  useEffect(() => {
    getLifeQuotes();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* <div className='quoteContainer'>
        {result.map(({ author, quote }, index) => (
          <div className='quoteContainer' key={index}>
            <h1>{author}</h1>
            <p>{quote}</p>
          </div>
        ))}
      </div> */}
    </div>
  );
}
